#include "ThemeManager.h"
#include "Colors.h"
#include <QApplication>

namespace AMAS {

QString ThemeManager::getStyleSheet() {
    using namespace Theme::Colors;

    // Build the stylesheet string utilizing token interpolations
    return QString(
        // Base elements and background colors
        "QWidget { "
        "  background-color: %1; "
        "  color: %2; "
        "  font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Arial, sans-serif; "
        "  font-size: 13px; "
        "} "
        "QMainWindow { "
        "  background-color: %1; "
        "} "

        // Menu Bar & Menu items
        "QMenuBar { "
        "  background-color: %3; "
        "  border-bottom: 1px solid %4; "
        "  padding: 2px 6px; "
        "} "
        "QMenuBar::item { "
        "  background-color: transparent; "
        "  padding: 6px 12px; "
        "  border-radius: 4px; "
        "} "
        "QMenuBar::item:selected { "
        "  background-color: %4; "
        "} "
        "QMenu { "
        "  background-color: %3; "
        "  border: 1px solid %4; "
        "  padding: 4px; "
        "} "
        "QMenu::item { "
        "  padding: 6px 24px; "
        "  border-radius: 4px; "
        "} "
        "QMenu::item:selected { "
        "  background-color: %5; "
        "  color: %2; "
        "} "
        "QMenu::separator { "
        "  height: 1px; "
        "  background-color: %4; "
        "  margin: 6px 0px; "
        "} "

        // Tool Bar
        "QToolBar { "
        "  background-color: %3; "
        "  border-bottom: 1px solid %4; "
        "  spacing: 8px; "
        "  padding: 6px; "
        "} "
        "QToolButton { "
        "  background-color: transparent; "
        "  border: 1px solid transparent; "
        "  border-radius: 4px; "
        "  padding: 6px 12px; "
        "  font-weight: bold; "
        "  color: %2; "
        "} "
        "QToolButton:hover { "
        "  background-color: %4; "
        "  border-color: %4; "
        "} "
        "QToolButton:pressed { "
        "  background-color: %5; "
        "} "

        // Status Bar
        "QStatusBar { "
        "  background-color: %3; "
        "  border-top: 1px solid %4; "
        "  color: %6; "
        "} "
        "QStatusBar::item { "
        "  border: none; "
        "} "

        // Standard Buttons
        "QPushButton { "
        "  background-color: %3; "
        "  border: 1px solid %4; "
        "  border-radius: 6px; "
        "  padding: 6px 16px; "
        "  font-weight: 500; "
        "  color: %2; "
        "} "
        "QPushButton:hover { "
        "  background-color: %4; "
        "  border-color: %5; "
        "} "
        "QPushButton:pressed { "
        "  background-color: %5; "
        "} "
        "QPushButton:disabled { "
        "  background-color: %1; "
        "  color: #555555; "
        "  border-color: #2D2D30; "
        "} "

        // Cards & Layout Panels (represented by QGroupBox)
        "QGroupBox { "
        "  background-color: %7; "
        "  border: 1px solid %4; "
        "  border-radius: 8px; "
        "  margin-top: 16px; "
        "  padding: 12px; "
        "} "
        "QGroupBox::title { "
        "  subcontrol-origin: margin; "
        "  subcontrol-position: top left; "
        "  left: 12px; "
        "  padding: 0px 6px; "
        "  font-weight: bold; "
        "  color: %5; "
        "} "

        // Stacked View layout
        "QStackedWidget { "
        "  background-color: %1; "
        "} "

        // Inline labels
        "QLabel { "
        "  background-color: transparent; "
        "  color: %2; "
        "} "

        // Input Fields (Text Edit, Spinboxes)
        "QLineEdit, QSpinBox, QDoubleSpinBox { "
        "  background-color: %1; "
        "  border: 1px solid %4; "
        "  border-radius: 4px; "
        "  padding: 5px 8px; "
        "  color: %2; "
        "} "
        "QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus { "
        "  border-color: %5; "
        "} "

        // Dropdowns (Combo Boxes)
        "QComboBox { "
        "  background-color: %1; "
        "  border: 1px solid %4; "
        "  border-radius: 4px; "
        "  padding: 5px 28px 5px 8px; "
        "  color: %2; "
        "} "
        "QComboBox:focus { "
        "  border-color: %5; "
        "} "
        "QComboBox::drop-down { "
        "  subcontrol-origin: padding; "
        "  subcontrol-position: top right; "
        "  width: 20px; "
        "  border-left: none; "
        "} "
        "QComboBox QAbstractItemView { "
        "  background-color: %3; "
        "  border: 1px solid %4; "
        "  selection-background-color: %5; "
        "} "

        // Tables, Trees, Lists
        "QTableWidget, QTreeWidget { "
        "  background-color: %7; "
        "  border: 1px solid %4; "
        "  gridline-color: %4; "
        "  border-radius: 6px; "
        "  selection-background-color: %5; "
        "  selection-color: %2; "
        "} "
        "QHeaderView::section { "
        "  background-color: %3; "
        "  color: %6; "
        "  padding: 6px; "
        "  border: 1px solid %4; "
        "  font-weight: bold; "
        "} "

        // Progress bar indicators
        "QProgressBar { "
        "  border: 1px solid %4; "
        "  border-radius: 4px; "
        "  text-align: center; "
        "  background-color: %1; "
        "} "
        "QProgressBar::chunk { "
        "  background-color: %5; "
        "  border-radius: 3px; "
        "} "

        // Custom Tabs styling
        "QTabWidget::pane { "
        "  border: 1px solid %4; "
        "  border-radius: 6px; "
        "  background-color: %7; "
        "} "
        "QTabBar::tab { "
        "  background-color: %3; "
        "  border: 1px solid %4; "
        "  padding: 8px 18px; "
        "  border-top-left-radius: 4px; "
        "  border-top-right-radius: 4px; "
        "} "
        "QTabBar::tab:selected { "
        "  background-color: %7; "
        "  border-bottom-color: transparent; "
        "  color: %5; "
        "  font-weight: bold; "
        "} "

        // Custom clean scrollbars
        "QScrollBar:vertical { "
        "  border: none; "
        "  background-color: %1; "
        "  width: 12px; "
        "  margin: 0px; "
        "} "
        "QScrollBar::handle:vertical { "
        "  background-color: %4; "
        "  min-height: 20px; "
        "  border-radius: 6px; "
        "} "
        "QScrollBar::handle:vertical:hover { "
        "  background-color: %6; "
        "} "
        "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { "
        "  border: none; "
        "  background: none; "
        "  height: 0px; "
        "} "
        "QScrollBar:horizontal { "
        "  border: none; "
        "  background-color: %1; "
        "  height: 12px; "
        "  margin: 0px; "
        "} "
        "QScrollBar::handle:horizontal { "
        "  background-color: %4; "
        "  min-width: 20px; "
        "  border-radius: 6px; "
        "} "
        "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { "
        "  border: none; "
        "  background: none; "
        "  width: 0px; "
        "} "

        // Dock widgets panel decoration
        "QDockWidget { "
        "  border: 1px solid %4; "
        "} "
        "QDockWidget::title { "
        "  background-color: %3; "
        "  padding: 6px; "
        "  font-weight: bold; "
        "} "
    )
    .arg(Background)    // %1
    .arg(TextPrimary)   // %2
    .arg(Surface)       // %3
    .arg(Border)        // %4
    .arg(Accent)        // %5
    .arg(TextSecondary) // %6
    .arg(Card);         // %7
}

void ThemeManager::applyTheme(QApplication *app, const QString &themeName) {
    Q_UNUSED(themeName);
    if (app) {
        app->setStyleSheet(getStyleSheet());
    }
}

} // namespace AMAS
